import React, { useMemo, useState } from "react";
import { ArrowLeft, ExternalLink, Copy, Check, ChevronDown, ChevronUp, Share2, Download, MessageSquare, CalendarDays, FileImage, Target, Globe2, ShieldCheck, ShieldAlert, CheckCircle2, XCircle, Info, Search, GitCompareArrows, Image as ImageIcon } from "lucide-react";
import { VerificationResult, VerificationSource } from "../types";
import { motion, AnimatePresence } from "motion/react";

interface ResultViewProps { result: VerificationResult; onReset: () => void; inputPreviewUrl?: string | null; }

const text = (v?: string | null) => (v || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const safeUrl = (value?: string | null): string | null => { if (!value) return null; try { const u = new URL(value); if (!["http:","https:"].includes(u.protocol) || !u.hostname || u.hostname==="example.com" || u.hostname==="localhost") return null; return u.toString(); } catch { return null; } };
const host = (url?: string | null) => { const u=safeUrl(url); if(!u)return ""; try{return new URL(u).hostname.replace(/^www\./,"");}catch{return "";} };
const verdictMeta = (verdict:string) => { const v=verdict.toUpperCase(); if(v==="TRUE"||v==="LIKELY TRUE")return{tone:"true",label:verdict,icon:CheckCircle2,title:"Supported by the available evidence."}; if(v==="FALSE"||v==="LIKELY FALSE"||v==="MISLEADING")return{tone:"false",label:verdict,icon:XCircle,title:"The available evidence conflicts with the claim."}; return{tone:"mixed",label:verdict,icon:Info,title:"The available evidence does not support a definitive conclusion."}; };
const relation = (s:VerificationSource) => { const r=(s.relationship||"NEUTRAL").toUpperCase(); if(r==="SUPPORTS")return{label:"Supports",cls:"result-rel-support",icon:CheckCircle2}; if(r==="CONTRADICTS")return{label:"Contradicts",cls:"result-rel-contradict",icon:XCircle}; if(r==="CONTEXT")return{label:"Related",cls:"result-rel-related",icon:Info}; return{label:"Neutral",cls:"result-rel-neutral",icon:Info}; };
const sourceType = (s:VerificationSource) => { const h=host(s.url||s.canonicalUrl),c=(s.category||"").toLowerCase(); if(c.includes("official")||/\.gov(\.in)?$|\.nic\.in$|\.mil$/.test(h)||/who\.int|un\.org|nasa\.gov/.test(h))return"Government / Official"; if(c.includes("research")||/nature\.com|science\.org|arxiv\.org|nih\.gov|pubmed/.test(h))return"Research"; if(c.includes("fact"))return"Fact Check"; if(c.includes("news"))return"News Article"; if(c.includes("historical"))return"Archive / Context"; return"Web Source"; };

const SourceRow:React.FC<{source:VerificationSource;index:number}>=({source,index})=>{ const url=safeUrl(source.url||source.canonicalUrl),rel=relation(source),RelIcon=rel.icon,publisher=text(source.publisher)||host(url)||"Source"; return <div className="tl-source-row">
  <div className="tl-source-rank">{index+1}</div>
  <div className="tl-source-main"><div className="tl-source-title"><strong>{publisher}</strong>{url&&<span>{host(url)}</span>}</div><div className="tl-source-description">{text(source.title)||"Verified source record"}</div><div className="tl-source-url">{url||"No validated URL available"}</div></div>
  <div className={`tl-rel-pill ${rel.cls}`}><RelIcon className="w-3 h-3"/>{rel.label}</div><div className="tl-source-type">{sourceType(source)}</div><div className="tl-source-date">{text(source.date||source.publishedDate)||"—"}</div>
  {url?<a className="tl-open-btn" href={url} target="_blank" rel="noopener noreferrer">Open <ExternalLink className="w-3 h-3"/></a>:<span className="tl-open-disabled">Unavailable</span>}
</div>;};

export const ResultView:React.FC<ResultViewProps>=({result,onReset,inputPreviewUrl})=>{
 const[copied,setCopied]=useState(false); const[auditOpen,setAuditOpen]=useState(false);
 const sources=useMemo(()=> (result.sources||[]).filter(s=>Boolean(s.title||s.url||s.canonicalUrl)),[result.sources]);
 const verifiedSources=sources.filter(s=>Boolean(s.isVerified&&safeUrl(s.url||s.canonicalUrl)));
 const supporting=result.supportingEvidence||[],contradicting=result.contradictingEvidence||[],context=result.contextEvidence||result.context||[],timeline=result.timelineItems||result.timeline||[];
 const meta=verdictMeta(result.verdict),VerdictIcon=meta.icon,isMedia=result.contentType==="image",hasDocument=result.contentType==="pdf"||result.contentType==="document";
 const evidenceTotal=supporting.length+contradicting.length+context.length;
 const independent=result.searchTransparency?.independentSourcesFound??new Set(verifiedSources.map(s=>s.independence)).size;
 const supportCount=result.searchTransparency?.supportingSourcesFound??sources.filter(s=>s.relationship==="SUPPORTS").length;
 const contradictCount=result.searchTransparency?.contradictingSourcesFound??sources.filter(s=>s.relationship==="CONTRADICTS").length;
 const relatedCount=sources.filter(s=>s.relationship==="CONTEXT").length;

 const copyReport=async()=>{const lines=["TruthLens Verification Report","",`Verdict: ${result.verdict}`,`Claim: ${text(result.claim)}`,`Evidence strength: ${result.evidenceStrength||"Not specified"}`,`Confidence: ${result.confidence}%`,"",`Why: ${text(result.why)}`,supporting.length?`\\nSupporting:\\n${supporting.map(x=>`• ${text(x)}`).join("\\n")}`:"",contradicting.length?`\\nContradicting:\\n${contradicting.map(x=>`• ${text(x)}`).join("\\n")}`:"",context.length?`\\nContext:\\n${context.map(x=>`• ${text(x)}`).join("\\n")}`:"",`\\nSources:\\n${verifiedSources.map(s=>`• ${text(s.publisher)||host(s.url)} — ${text(s.title)} — ${s.url}`).join("\\n")||"No validated source URLs available."}`].join("\\n");try{await navigator.clipboard.writeText(lines);setCopied(true);window.setTimeout(()=>setCopied(false),1600);}catch{}};
 const share=async()=>{try{if(navigator.share)await navigator.share({title:"TruthLens Verification",text:`TruthLens: ${result.verdict} — ${text(result.claim)}`});else await navigator.clipboard.writeText(`TruthLens: ${result.verdict} — ${text(result.claim)}`);}catch{}};
 const downloadReport=()=>{const content=["TRUTHLENS — VERIFICATION REPORT","",`VERDICT: ${result.verdict}`,`CONFIDENCE: ${result.confidence}%`,`EVIDENCE: ${result.evidenceStrength||"Not specified"}`,"",`CLAIM: ${text(result.claim)}`,"",`WHY: ${text(result.why)}`,"","SOURCES:",...verifiedSources.map((s,i)=>`${i+1}. ${text(s.publisher)||host(s.url)} — ${text(s.title)} — ${s.url}`)].join("\\n");const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="truthlens-verification-report.txt";a.click();URL.revokeObjectURL(a.href);};

 return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="truthlens-report">
  <div className="tl-report-topbar"><button onClick={onReset} className="tl-back"><ArrowLeft className="w-4 h-4"/> Back to Search</button><div className="tl-report-actions"><button onClick={share}><Share2 className="w-3.5 h-3.5"/> Share</button><button onClick={downloadReport}><Download className="w-3.5 h-3.5"/> Download Report</button><button onClick={copyReport}><MessageSquare className="w-3.5 h-3.5"/> {copied?"Copied":"Feedback"}</button></div></div>

  <div className="tl-report-grid">
   <section className="tl-media-card"><div className="tl-main-media">{inputPreviewUrl?<img src={inputPreviewUrl} alt="Submitted verification input"/>:<div className="tl-media-placeholder"><ImageIcon className="w-10 h-10"/><span>{hasDocument?"Submitted document":"Text claim"}</span></div>}{inputPreviewUrl&&<button className="tl-original-btn" onClick={()=>window.open(inputPreviewUrl,"_blank","noopener,noreferrer")}><ExternalLink className="w-3.5 h-3.5"/> View Original <ExternalLink className="w-3 h-3"/></button>}</div><div className="tl-media-strip"><div className="tl-thumb active">{inputPreviewUrl?<img src={inputPreviewUrl} alt=""/>:<FileImage className="w-5 h-5"/>}</div><div className="tl-thumb"><GitCompareArrows className="w-5 h-5"/></div><div className="tl-thumb"><Search className="w-5 h-5"/></div><div className="tl-more-thumb">+{Math.max(1,Math.min(4,sources.length))} more</div></div></section>

   <section className={`tl-verdict-card tl-verdict-${meta.tone}`}><div className="tl-verdict-heading"><div className="tl-verdict-icon"><VerdictIcon className="w-9 h-9"/></div><div className="tl-verdict-copy"><span>Verdict</span><h1>{meta.label}</h1><p>{meta.title}</p></div><div className="tl-confidence-pill"><ShieldCheck className="w-3.5 h-3.5"/> {result.confidenceLabel||"Confidence"} · {result.confidence}%</div></div>
    <div className="tl-verdict-meta"><div><CalendarDays/><span>Checked<strong>{result.analyzedAt?new Date(result.analyzedAt).toLocaleString([],{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—"}</strong></span></div><div><FileImage/><span>Input Type<strong>{isMedia?"Image (JPG)":hasDocument?(result.contentType==="pdf"?"PDF Document":"DOCX Document"):"Text Claim"}</strong></span></div><div><Target/><span>Claim Category<strong>{result.claimType||"Factual claim"}</strong></span></div><div><Globe2/><span>Sources<strong>{verifiedSources.length} validated · {independent} independent</strong></span></div></div>
    <div className="tl-claim-box"><div className="tl-claim-head"><strong>Extracted Claim</strong><button onClick={copyReport}>Copy</button></div><p>“{text(result.claim)}”</p></div>
   </section>
  </div>

  <div className="tl-two-col">
   <section className="tl-panel tl-evidence-strength"><div className="tl-panel-title"><h2>Evidence Strength</h2><span>i</span></div><div className="tl-strength-layout"><div className="tl-ring-wrap"><div className="tl-ring" style={{"--score":Math.max(0,Math.min(100,result.confidence))} as React.CSSProperties}><div><strong>{result.confidence}%</strong><span>{result.evidenceStrength?result.evidenceStrength.replace(" Evidence",""):"Evidence"}</span></div></div><b>{result.evidenceStrength||"Evidence assessed"}</b><small>Based on {Math.max(verifiedSources.length,independent||0)} validated sources</small></div><div className="tl-count-list"><div><i className="dot green"/> Supporting sources <strong>{supportCount}</strong></div><div><i className="dot red"/> Contradicting sources <strong>{contradictCount}</strong></div><div><i className="dot blue"/> Related / Context <strong>{relatedCount}</strong></div><div className="tl-evidence-note"><ShieldCheck className="w-4 h-4"/>{evidenceTotal?"Evidence points are separated by how they relate to the claim.":"No structured evidence points were returned; review the source trail before relying on the verdict."}</div></div></div></section>

   <section className="tl-panel"><div className="tl-panel-title"><h2>Why this verdict?</h2></div><div className="tl-why-block"><div className={`tl-why-icon ${meta.tone==="false"?"false":"info"}`}><VerdictIcon className="w-5 h-5"/></div><div><b>{meta.tone==="false"?"What’s False or Misleading?":"What the evidence indicates"}</b><ul><li>{text(result.why)}</li>{result.truthCorrection&&<li>{text(result.truthCorrection)}</li>}</ul></div></div>{supporting.length>0&&<div className="tl-why-block"><div className="tl-why-icon true"><CheckCircle2 className="w-5 h-5"/></div><div><b>What’s Supported?</b><ul>{supporting.slice(0,3).map((x,i)=><li key={i}>{text(x)}</li>)}</ul></div></div>}{context.length>0&&<div className="tl-why-block"><div className="tl-why-icon info"><Info className="w-5 h-5"/></div><div><b>Additional Context</b><ul>{context.slice(0,3).map((x,i)=><li key={i}>{text(x)}</li>)}</ul></div></div>}</section>
  </div>

  <div className="tl-two-col">
   <section className="tl-panel tl-graph"><div className="tl-panel-title"><h2>Evidence Graph</h2><span>i</span><button className="tl-help">⊕ How to read?</button></div><div className="tl-graph-stage"><div className="tl-graph-node claim"><b>Claim</b><span>{text(result.claim).slice(0,90)}{text(result.claim).length>90?"…":""}</span></div><div className="tl-graph-sources">{sources.filter(s=>["SUPPORTS","CONTRADICTS","CONTEXT"].includes(s.relationship||"")).slice(0,3).map((s,i)=>{const r=relation(s);return <div className="tl-graph-source" key={i}><span className={r.cls}>{r.label}</span><b>{text(s.publisher)||host(s.url)}</b><small>{text(s.title).slice(0,52)}</small></div>;})}{sources.length===0&&<div className="tl-graph-empty">No validated evidence nodes available.</div>}</div><div className="tl-graph-conclusion"><b>Conclusion</b><span>{text(result.bottomLine||result.why).slice(0,180)}</span></div></div></section>

   <section className="tl-panel tl-comparison"><div className="tl-panel-title"><h2>{isMedia?"Image Comparison":"Input Comparison"}</h2><span className="tl-side-badge">Side-by-side analysis</span></div><div className="tl-compare-grid"><div className="tl-compare-item">{inputPreviewUrl?<img src={inputPreviewUrl} alt=""/>:<div className="tl-compare-empty"><ImageIcon/></div>}<b>Your Input</b><small>{isMedia?"(Submitted Image)":"(Submitted Claim)"}</small></div><div className="tl-compare-item"><div className="tl-compare-empty"><Search/></div><b>Reference Evidence</b><small>{verifiedSources[0]?text(verifiedSources[0].publisher):"No reference media available"}</small></div></div><div className="tl-compare-note"><ShieldCheck className="w-4 h-4"/> TruthLens only shows reference media when an actual media asset is available.</div></section>
  </div>

  {timeline.length>0&&<section className="tl-panel tl-timeline"><div className="tl-panel-title"><h2>Timeline</h2></div><div className="tl-timeline-track">{timeline.slice(0,5).map((item,i)=><div className="tl-timeline-item" key={i}><span className="tl-timeline-dot"/><b>{text(item.date)}</b><p>{text(item.event)}</p></div>)}</div></section>}

  <section className="tl-panel tl-trail"><div className="tl-panel-title"><h2>Evidence Trail <small>(Top Sources)</small></h2><span className="tl-count-badge">{verifiedSources.length} validated</span></div><div className="tl-source-table"><div className="tl-source-head"><span>#</span><span>Source</span><span>Title / Description</span><span>Date</span><span>Relationship</span><span>Type</span><span>Actions</span></div>{verifiedSources.slice(0,6).map((s,i)=><SourceRow source={s} index={i} key={i}/>)}{verifiedSources.length===0&&<div className="tl-no-sources"><ShieldAlert className="w-5 h-5"/><div><b>No validated source URLs</b><p>TruthLens will not display an invented or unvalidated source link.</p></div></div>}</div></section>

  <div className="tl-share-banner"><div><ShieldCheck className="w-7 h-7"/><span><b>Be Informed, Share Responsibly.</b><small>Help stop the spread of misinformation. Verify before you believe.</small></span></div><em>“Facts don’t take sides. People do.”<br/>— TruthLens</em></div>
  <section className="tl-audit-wrap"><button className="tl-audit-button" onClick={()=>setAuditOpen(v=>!v)}><span><Search className="w-4 h-4"/> Research & Audit Details</span>{auditOpen?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button><AnimatePresence initial={false}>{auditOpen&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="tl-audit-content">{result.searchTransparency&&<div className="tl-audit-grid">{[["Sources found",result.searchTransparency.sourcesFound],["Sources evaluated",result.searchTransparency.sourcesEvaluated],["Official sources",result.searchTransparency.officialSourcesFound],["Independent",result.searchTransparency.independentSourcesFound]].map(([k,v])=><div key={String(k)}><strong>{v}</strong><span>{k}</span></div>)}</div>}{(result.disputedPoints||result.uncertainties||[]).length>0&&<div><b>Uncertainties & disputed points</b><ul>{(result.disputedPoints||result.uncertainties||[]).map((x,i)=><li key={i}>{text(x)}</li>)}</ul></div>}{result.detailedAnalysis?.sourceComparison&&<div><b>Source comparison</b><p>{text(result.detailedAnalysis.sourceComparison)}</p></div>}</motion.div>}</AnimatePresence></section>
  <div className="tl-final-note"><ShieldAlert className="w-4 h-4"/><p><b>Important:</b> AI-assisted verification can make mistakes. For high-stakes claims, open the original sources and inspect the underlying evidence yourself.</p></div>
  <button onClick={onReset} className="tl-new-check"><ArrowLeft className="w-4 h-4"/> Verify Another Claim</button>
 </motion.div>;
};
export default ResultView;